Repository denysdovhan/chernivtsi-transport, pull requests merged in 2018-12, with the labels that each got.

#11 Use React
  .gitignore
  app/README.md
  app/index.html
  app/package.json
  app/public/favicon.ico
  app/public/index.html
  app/public/manifest.json
  app/src/App.js
  app/src/index.css
  app/src/index.js
  app/src/serviceWorker.js
  app/src/sse-client.js
  app/src/svg.js
  app/yarn.lock
  index.js
  package-lock.json
  package.json
Labels: client

#13 Add .editorconfig file
  .editorconfig
Labels: infrastructure

#17 Move API code to api folder
  api/data-provider.js
  api/event-stream.js
  api/index.js
  api/package.json
  api/trans-gps.js
  api/transport-cv.js
  api/yarn.lock
  yarn.lock
Labels: server
